https:
  host: "0.0.0.0"
  port: "8082"
  protocol: "HTTPS"
  basepath: "/"
  
database:
  host: "mysql-79196-0.cloudclusters.net"
  port: "13233"
  username: "admin"
  password: "X5uZddwV"
  name: "BookMyShowTickets"
  
keystore:
  client:
    path: "clientkeystore.jks"
    type: "JKS"
    alias: "myclient"
    keypassword: "password"
    password: "password"
  
  server:
    path: "serverkeystore.jks"
    type: "JKS"
    alias: "myserver"
    keypassword: "password"
    password: "password"
    


truststore:
  client:
    path: "clienttruststore.jks"
    type: "JKS"
    keypassword: "password"
  server:
    path: "servertruststore.jks"
    type: "JKS"
    keypassword: "password" 