#%RAML 1.0 DataType
type: object
properties: 
  BookingID: integer
  MovieID: integer
  MovieName: string
  Language: string
  TheatreName: string
  TheatreID: string
  TotalTickets: integer
  BookedTickets: integer
  Username: string
  BookingStatus: string